'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _eyes = require('eyes');

var eyes = _interopRequireWildcard(_eyes);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

// Generated by CoffeeScript 2.0.0-beta2
var inspect;

inspect = eyes.inspector({
  pretty: true,
  hideFunctions: true,
  stream: process.stdout,
  maxLength: 204800
});

exports.default = inspect;

